# Generated by Django 5.2.4 on 2025-07-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0002_alter_category_cat_image_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
